export enum VidtPresets {
    '____EMPTY____',
    'bluescreen',
    'color',
    'colorBlocks',
    'colorGlitch',
    'colorTwinkle',
    'gridscape',
    'hacking',
    'kaleido',
    'karaoke',
    'logo',
    'multicolor',
    'photoBlocks',
    'photobouncer',
    'photoglitcher',
    'shutdown',
    'textBouncer',
    'videoPlayer',
    'vista',
    'wheel',
}
//
// export enum VidtPresets {
//     EMPTY = '____EMPTY____',
//     BLUESCREEN = 'bluescreen',
//     COLOR = 'color',
//     COLOR_BLOCKS = 'colorblocks',
//     COLOR_GLITCH = 'colorglitch',
//     COLOR_TWINKLE = 'color-twinkle',
//     GRIDSCAPE = 'gridscape',
//     HACKING = 'hacking',
//     KALEIDO = 'kaleido',
//     KARAOKE = 'karaoke',
//     LOGO = 'logo',
//     PHOTO_BLOCKS = 'photo-blocks',
//     PHOTOBOUNCER = 'photobouncer',
//     PHOTOGLITCHER = 'photoglitcher',
//     SHUTDOWN = 'shutdown',
//     TEXT_BOUNCER = 'textbouncer',
//     VIDEOPLAYER = 'videoplayer',
//     VISTA = 'vista',
//     WHEEL = 'wheel',
// }
