export enum VidtPresets {
    '____EMPTY____',
    'logo',
    'bluescreen',
    'color',
    // 'multicolor',
    'gridscape',
    'hacking',
    'photobouncer',
    'photoglitcher',
    'textBouncer',
    'shutdown',
    // 'video',
    'vista',
    'colorTwinkle',
    'karaoke',
    'colorBlocks',
    'kaleido',
}
