export enum VidtPresets {
    '____EMPTY____',
    'bluescreen',
    'color',
    'colorBlocks',
    'colorGlitch',
    'colorTwinkle',
    'gridscape',
    'hacking',
    'kaleido',
    'kaleidoMulti',
    'karaoke',
    'logo',
    'multicolor',
    'photoBlocks',
    'photobouncer',
    'photoglitcher',
    'shutdown',
    'textBouncer',
    'vista',
    'wheel',
    // 'video',
}
