export const words: string[] = [
    'STROBOCOPS',
    'DANCE',
    'YOLO',
    'MAN',
    'VROUW',
    'ALLEMAAL',
    'NEUKEN',
    'HARDER',
    'RAUWER',
    'GLADDER',
    'CABRIO',
    'CABRIOLETTA',
    'LAST CHRISTMAS',
    'I GAVE YOU MY HEART',
    'HEART',
    'CODEMONKEYS',
    'GEJAT',
    '<<<<<<< HEAD <fuck><conflict> >>>>>>> master <fuckyou><im master>'
];
